cask_args force: true

cask "google-chrome"
cask "wezterm"
cask "temurin"
cask "another-redis-desktop-manager"
cask "pgadmin4"
cask "insomnia"
cask "obsidian"
cask "cursor"

brew "fish"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "wget"
brew "borkdude/brew/babashka"
brew "lazygit"
brew "n"
brew "gh"
brew "clojure/tools/clojure"
brew "docker"
brew "docker-compose"
brew "colima"
brew "rbenv"
brew "uv"
brew "ollama"
